version: '3'

services:
    database:
        container_name: database
        image: postgres:13.0
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: dbtest
        ports:
            - 15432:5432
    php:
        container_name: "php-fpm"
        build:
            context: ./docker/php
        depends_on:
            - database
        volumes:
            - ./project/:/var/www
    nginx:
        container_name: "nginx"
        build:
            context: ./docker/nginx
        volumes:
            - ./project/:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/logs:/var/log
        depends_on:
            - php
        ports:
            - "80:80"